config/routes.rb
Rails.application.routes.draw do
  
  root 'application#hello'

  resources :teddybears
  resources :users
  resources :notebooks
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  validates :name, presence: true
  
  belongs_to :user
  has_many :pages
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.html { redirect_to @notebook, notice: 'Notebook was successfully created.' }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to @notebook, notice: 'Notebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.html { redirect_to notebooks_url, notice: 'Notebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notebook_params
      params.fetch(:notebook, {})
    end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.erb
<%= form_for(notebook) do |f| %>
  <% if notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
      <% notebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notebooks/edit.html.erb
<h1>Editing Notebook</h1>

<%= render 'form', notebook: @notebook %>

<%= link_to 'Show', @notebook %> |
<%= link_to 'Back', notebooks_path %>

app/views/notebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notebooks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notebooks.each do |notebook| %>
      <tr>
        <td><%= link_to 'Show', notebook %></td>
        <td><%= link_to 'Edit', edit_notebook_path(notebook) %></td>
        <td><%= link_to 'Destroy', notebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notebook', new_notebook_path %>

app/views/notebooks/new.html.erb
<h1>New Notebook</h1>

<%= render 'form', notebook: @notebook %>

<%= link_to 'Back', notebooks_path %>

app/views/notebooks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_notebook_path(@notebook) %> |
<%= link_to 'Back', notebooks_path %>