config/routes.rb
Rails.application.routes.draw do
  
  root 'application#hello'

  resources :teddybears
  resources :users
  resources :notebooks
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teddybear.rb
class Teddybear < ApplicationRecord
end

app/controllers/teddybears_controller.rb
class TeddybearsController < ApplicationController
  before_action :set_teddybear, only: [:show, :edit, :update, :destroy]

  # GET /teddybears
  # GET /teddybears.json
  def index
    @teddybears = Teddybear.all
  end

  # GET /teddybears/1
  # GET /teddybears/1.json
  def show
  end

  # GET /teddybears/new
  def new
    @teddybear = Teddybear.new
  end

  # GET /teddybears/1/edit
  def edit
  end

  # POST /teddybears
  # POST /teddybears.json
  def create
    @teddybear = Teddybear.new(teddybear_params)

    respond_to do |format|
      if @teddybear.save
        format.html { redirect_to @teddybear, notice: 'Teddybear was successfully created.' }
        format.json { render :show, status: :created, location: @teddybear }
      else
        format.html { render :new }
        format.json { render json: @teddybear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teddybears/1
  # PATCH/PUT /teddybears/1.json
  def update
    respond_to do |format|
      if @teddybear.update(teddybear_params)
        format.html { redirect_to @teddybear, notice: 'Teddybear was successfully updated.' }
        format.json { render :show, status: :ok, location: @teddybear }
      else
        format.html { render :edit }
        format.json { render json: @teddybear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teddybears/1
  # DELETE /teddybears/1.json
  def destroy
    @teddybear.destroy
    respond_to do |format|
      format.html { redirect_to teddybears_url, notice: 'Teddybear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teddybear
      @teddybear = Teddybear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teddybear_params
      params.require(:teddybear).permit(:name, :email)
    end
end

app/helpers/teddybears_helper.rb
module TeddybearsHelper
end

app/views/teddybears/_form.html.erb
<%= form_for(teddybear) do |f| %>
  <% if teddybear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teddybear.errors.count, "error") %> prohibited this teddybear from being saved:</h2>

      <ul>
      <% teddybear.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teddybears/edit.html.erb
<h1>Editing Teddybear</h1>

<%= render 'form', teddybear: @teddybear %>

<%= link_to 'Show', @teddybear %> |
<%= link_to 'Back', teddybears_path %>

app/views/teddybears/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teddybears</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teddybears.each do |teddybear| %>
      <tr>
        <td><%= teddybear.name %></td>
        <td><%= teddybear.email %></td>
        <td><%= link_to 'Show', teddybear %></td>
        <td><%= link_to 'Edit', edit_teddybear_path(teddybear) %></td>
        <td><%= link_to 'Destroy', teddybear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teddybear', new_teddybear_path %>

app/views/teddybears/new.html.erb
<h1>New Teddybear</h1>

<%= render 'form', teddybear: @teddybear %>

<%= link_to 'Back', teddybears_path %>

app/views/teddybears/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teddybear.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teddybear.email %>
</p>

<%= link_to 'Edit', edit_teddybear_path(@teddybear) %> |
<%= link_to 'Back', teddybears_path %>